/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './App.{js,jsx,ts,tsx}',
    './screens/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{tsx,jsx}',
    './',
  ],
  theme: {
    extend: {
      fontFamily: {
        openSans: ['OpenSans-Regular'],
        openSansBold: ['OpenSans-Bold'],
        openSansItalic: ['OpenSans-Italic'],
        openSansSemiBold: ['OpenSans-SemiBold'],
        openSansBoldItalic: ['OpenSans_-oldItalic'],
        openSansMedium: ['OpenSans-Medium'],
        openSansMediumItalic: ['OpenSans-MediumItalic'],
        openSansLight: ['OpenSans-Light'],
        openSansLightItalic: ['OpenSans-LightItalic'],
        openSansExtraLight: ['OpenSans-ExtraLight'],
        openSansExtraLightItalic: ['OpenSans-ExtraLightItalic'],
        roboto: ['Roboto-Regular'],
        robotoBold: ['Roboto-Bold'],
        robotoSemiBold: ['Robot-SemiBold'],
        robotoItalic: ['Roboto-Italic'],
        robotoMedium: ['Robot-Medium'],
        robotoMediumItalic: ['Roboto-MediumItalic'],
        robotoLight: ['Roboto-Light'],
        robotoLightItalic: ['Roboto-LightItalic'],
        robotoBlack: ['Roboto-Black'],
        robotoBlackItalic: ['Roboto-BlackItalic'],
        notoSans: ['NotoSans-Regular'],
        notoSansBold: ['NotoSans-Bold'],
        notoSansItalic: ['NotoSans-Italic'],
        notoSansSemiBold: ['NotoSans-SemiBold'],
        notoSansBoldItalic: ['NotoSans-BoldItalic'],
        notoSansMedium: ['NotoSans-Medium'],
        notoSansMediumItalic: ['NotoSans-MediumItalic'],
        notoSansLight: ['NotoSans-Light'],
        notoSansLightItalic: ['NotoSans-LightItalic'],
        notoSansExtraLight: ['NotoSans-ExtraLight'],
        notoSansExtraLightItalic: ['NotoSans-ExtraLightItalic'],
      },
    },
  },
  plugins: [],
};
